import random
import datetime
import json
import os

WIDTH = 60
HEIGHT = 20
WALL_PROBABILITY = 0.45
ITERATIONS = 5

START_MARKER = "<" + "!-- DAILY_MAP_START --" + ">"
END_MARKER = "<" + "!-- DAILY_MAP_END --" + ">"

class MapGenerator:
    def __init__(self, width, height, seed=None):
        self.width = width
        self.height = height
        self.grid = []
        
        if seed is None:
            today_str = datetime.date.today().strftime("%Y%m%d")
            self.seed = int(today_str)
        else:
            self.seed = seed
            
        random.seed(self.seed)

    def initialize_grid(self):
        """Randomly initialize the grid with walls and floors."""
        self.grid = [[1 if random.random() < WALL_PROBABILITY else 0 
                      for _ in range(self.width)] for _ in range(self.height)]

    def count_neighbors(self, x, y):
        """Count wall neighbors around (x, y)."""
        count = 0
        for i in range(-1, 2):
            for j in range(-1, 2):
                if i == 0 and j == 0:
                    continue
                nx, ny = x + i, y + j
                if nx < 0 or ny < 0 or nx >= self.width or ny >= self.height:
                    count += 1
                elif self.grid[ny][nx] == 1:
                    count += 1
        return count

    def simulation_step(self):
        new_grid = [[0 for _ in range(self.width)] for _ in range(self.height)]
        for y in range(self.height):
            for x in range(self.width):
                neighbors = self.count_neighbors(x, y)
                if neighbors > 4:
                    new_grid[y][x] = 1
                elif neighbors < 4:
                    new_grid[y][x] = 0
                else:
                    new_grid[y][x] = self.grid[y][x]
        self.grid = new_grid

    def generate(self):
        """Run the full generation process."""
        self.initialize_grid()
        for _ in range(ITERATIONS):
            self.simulation_step()
        return self.grid

    def get_ascii_art(self):
        """Convert grid to ASCII art."""
        ascii_map = ""
        for row in self.grid:
            line = "".join(["⬛" if cell == 1 else "⬜" for cell in row])
            ascii_map += line + "\n"
        return ascii_map

    def save_to_json(self, filename="today_map.json"):
        """Save map data to JSON file with compact grid rows."""
        data = {
            "date": datetime.date.today().isoformat(),
            "seed": self.seed,
            "width": self.width,
            "height": self.height
        }
        
        with open(filename, 'w') as f:
            json_str = json.dumps(data, indent=4)
            f.write(json_str[:-1])
            
            f.write(',\n    "grid": [\n')
            
            for i, row in enumerate(self.grid):
                row_str = json.dumps(row)
                
                if i < len(self.grid) - 1:
                    f.write(f'        {row_str},\n')
                else:
                    f.write(f'        {row_str}\n')
            
            f.write('    ]\n}')
            
        print(f"Map data saved to {filename}")

def update_readme(ascii_art, seed):
    """Update the README.md file with the new map and link."""
    readme_path = "README.md"
    
    if not os.path.exists(readme_path):
        print("README.md not found.")
        return

    with open(readme_path, "r", encoding="utf-8") as f:
        content = f.read()

    today = datetime.date.today().strftime("%Y/%m/%d")
    new_section = f"{START_MARKER}\n"
    new_section += f"### Today's Generated Map ({today})\n"
    new_section += "```\n"
    new_section += ascii_art
    new_section += "```\n"
    new_section += f"_Generated by Cellular Automata_\n\n"
    new_section += f"[Download Map Data (JSON)](./today_map.json) | **Seed:** `{seed}`\n"
    new_section += END_MARKER

    if START_MARKER in content and END_MARKER in content:
        before = content.split(START_MARKER)[0]
        after = content.split(END_MARKER)[1]
        new_content = before + new_section + after
        
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print("README updated successfully.")
    else:
        print("Markers not found in README.")

if __name__ == "__main__":
    generator = MapGenerator(WIDTH, HEIGHT)
    generator.generate()
    
    generator.save_to_json()
    
    ascii_map = generator.get_ascii_art()
    update_readme(ascii_map, generator.seed)
